import { ColorModeScript } from "@chakra-ui/react";
import { Head, Html, Main, NextScript } from "next/document";
import { theme } from "../styles/theme";

export default function MyDocument() {
  return (
    <Html>
      <title>Portfolio | Isaque</title>
      <Head>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="ico" href="/public/apple-touch-icon.png" /> */}

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <ColorModeScript initialColorMode={theme} />
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
