export default function Head() {
  return (
    <>
      <meta name="description" content="Generated by create next app" />

      <link rel="shortcut icon" href="/favicon/IS.svg" />

      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@400;500;700&display=swap"
        rel="stylesheet"
      />
    </>
  );
}
